applica/urls.py
from debug_toolbar.panels.alerts import AlertsPanel
from django.urls import path
from rest_framework import routers

from applica.apis import ExcesoVelocidadPorMesAPIView, IncidenciaPorMesAPIView, ExcesoVelocidadPorVehiculoAPIView, \
    IncidenciaPorConductorAPIView, InfraccionPorConductorAPIView, InfraccionPorMesAPIView
from applica.views import ReporteVelcidadTemplateView, AlertaRevisionTecnicaTemplateView, \
    ReporteIncidenciasTemplateView, \
    AlertaSoatTemplateView, ReporteIncidenciasChoferTemplateView, ReporteVelcidadVehiculoTemplateView, \
    ReporteInfraccionTemplateView, ReporteInfraccionConductorTemplateView

router = routers.SimpleRouter()

app_name = "applica"

urlpatterns = [

    path('reporte/alerta-revision', AlertaRevisionTecnicaTemplateView.as_view(), name='reporte_alerta_revision'),
    path('reporte/alerta-soat', AlertaSoatTemplateView.as_view(), name='reporte_alerta_soat'),
    path('reporete/incidencias', ReporteIncidenciasTemplateView.as_view(), name='reporte_incidencias'),
    path('reporete/incidencias-chofer', ReporteIncidenciasChoferTemplateView.as_view(),
         name='reporte_chofer_incidencias'),
    path('reporte/velocidad-vehiculo', ReporteVelcidadVehiculoTemplateView.as_view(),
         name='reporte_vehiculo_velocidad'),
    path('reporte/velocidad', ReporteVelcidadTemplateView.as_view(),
         name='reporte_velocidad'),

    path('reporete/infraccion', ReporteInfraccionTemplateView.as_view(), name='reporte_infraccion'),

    path('reporete/infraccion-chofer', ReporteInfraccionConductorTemplateView.as_view(),
         name='reporte_chofer_infraccion'),

    path('api/excesos-velocidad/<int:year>/', ExcesoVelocidadPorMesAPIView.as_view(), name='excesos-velocidad-por-mes'),
    path('api/excesos-velocidad-vehiculo/<int:year>/<str:month>/', ExcesoVelocidadPorVehiculoAPIView.as_view(),
         name='incidencias-por-vehiculo'),
    path('api/insidencias/<int:year>/', IncidenciaPorMesAPIView.as_view(), name='incidencias-por-mes'),
    path('api/insidencias-conductor/<int:year>/<str:month>/', IncidenciaPorConductorAPIView.as_view(),
         name='incidencias-por-conductor'),
    path('api/infraccion/<int:year>/', InfraccionPorMesAPIView.as_view(), name='infraccion-por-mes'),
    path('api/infraccion-conductor/<int:year>/<str:month>/', InfraccionPorConductorAPIView.as_view(),
         name='infraccion-por-conductor'),

]

urlpatterns = urlpatterns + router.urls

vehiculo/urls.py
from django.contrib import admin
from django.urls import path, include

from applica.sites import custom_admin_site
from applica.views import DashboardTemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("admin/", custom_admin_site.urls),

    # path("select2/", include("django_select2.urls")),

    path('', DashboardTemplateView.as_view(), name='dashboard'),

    path('app/', include('applica.urls', namespace='app')),
]

templates/layout/aside.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
         aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
                    aria-label="Close">
            </button>
        </div>

        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page"
                       href="{% url 'dashboard' %}">
                        <i class="bi bi-house-fill "></i>
                        Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2"
                       href="{% url 'app:reporte_velocidad' %}">
                        <i class="bi bi-file-earmark"></i>
                        Reporte Velocidad
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2"
                       href="{% url 'app:reporte_vehiculo_velocidad' %}">
                        <i class="bi bi-file-earmark"></i>
                        Reporte Velocidad por vehiculo
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'app:reporte_alerta_revision' %}">
                        <i class="bi bi-cart"></i>
                        Revisiones Técnicas
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'app:reporte_alerta_soat' %}">
                        <i class="bi bi-cart"></i>
                        Soats
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'app:reporte_incidencias' %}">

                        <i class="bi bi-people"></i>
                        Incidencias
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2"
                       href="{% url 'app:reporte_chofer_incidencias' %}">

                        <i class="bi bi-people"></i>
                        Incidencias por Chofer
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'app:reporte_infraccion' %}">

                        <i class="bi bi-people"></i>
                        Infraccion
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2"
                       href="{% url 'app:reporte_chofer_infraccion' %}">

                        <i class="bi bi-people"></i>
                        Infraccion por Chofer
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="/admin/">
                        <i class="bi bi-graph-up"></i>
                        Admin
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>

templates/layout/base.html
<html lang="en" data-bs-theme="light">
{% load static %}
<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">


    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">

    <!-- Favicons -->

    <meta name="theme-color" content="#712cf9">


    <!-- Custom styles for this template -->

    <!-- Custom styles for this template -->
    <link href="{% static 'custom/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.min.css' %}">
</head>
<body>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (light)">

        <i class="bi bi-sun-fill my-1 theme-icon-active"></i>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="light"
                    aria-pressed="true">

                <i class="bi bi-sun-fill me-2 opacity-50"></i>
                Light

                <i class="bi bi-check2 ms-auto d-none"></i>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">

                <i class="bi bi-moon-stars-fill me-2 opacity-50"></i>
                Dark

                <i class="bi bi-check2 ms-auto d-none"></i>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto"
                    aria-pressed="false">

                <i class="bi bi-circle-half me-2 opacity-50 "></i>
                Auto

                <i class="bi bi-check2 ms-auto d-none"></i>
            </button>
        </li>
    </ul>
</div>


{% include 'layout/header.html' %}
<div class="container-fluid">
    <div class="row">
        {% include 'layout/aside.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <br>
            <div class="container">
                {% block content %}

                {% endblock %}
            </div>
        </main>
    </div>
</div>

<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.js' %}"></script>


</body>
{% block extra_js %}

{% endblock %}

{% block custom_js %}

{% endblock %}
</html>

templates/layout/header.html
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">Dorado App</a>

    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false"
                    aria-label="Toggle search">

                <i class="bi bi-search"></i>
            </button>
        </li>
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">

                <i class="bi bi-list"></i>
            </button>
        </li>
    </ul>

    <div id="navbarSearch" class="navbar-search w-100 collapse">
        <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
    </div>
</header>